[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/process-telegram"
  to = "/.netlify/functions/process-telegram"
  status = 200